import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react';

import { Alchemy, Network } from 'alchemy-sdk';

const inter = Inter({ subsets: ['latin'] })

const settings = {
  apiKey: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY,
  network: Network.ETH_MAINNET,
};
const alchemy = new Alchemy(settings);

export default function Home() {
  const [blockNumber, setBlockNumber] = useState<number | null>(null);

  useEffect(() => {
    const getBlockNumber = async () => {
      const blockNumber = await alchemy.core.getBlockNumber();
      setBlockNumber(blockNumber);
    }
    getBlockNumber();

    alchemy.ws.on("block", (blockNumber) =>
      setBlockNumber(blockNumber)
    );
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Latest Block: <span>{blockNumber}</span>
            </h2>
          </a>
        </div>
      </main>
    </>
  )
}